# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 670f8bab91517eb26b7f77bd84f49c9b76a05812c9a4bac4beb79cf858492c96df35f0d896b8d66c37e0b6df26ac56340c146fc7662b6f9ff6fd1c1f6ac446be

test:
  secret_key_base: 5ce7ad25d9e05e28b6db7c74084d040aada07cec695719e39b5d3c20ebf4218824643441bffebe977f226b68e6dbdd21881d0c187a2269abb2dfe4980e66f9cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
